name: Build and Package

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Build and Test
      shell: bash
      run: |
        chmod +x tests/build.sh tests/run-tests.sh
        ./tests/run-tests.sh --coverage

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: tests/coverage_report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: tests/build/coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Package
      working-directory: tests/build
      run: cpack -G TGZ -C Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Z80-package-ubuntu
        path: tests/build/*.tar.gz
        if-no-files-found: warn